//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_COMP2007_ExpenseTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost_tracking
    {
        public int EntryID { get; set; }
        public string userID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> bills { get; set; }
        public Nullable<decimal> food { get; set; }
        public Nullable<decimal> media { get; set; }
        public Nullable<decimal> clothing { get; set; }
        public Nullable<decimal> travel { get; set; }
        public Nullable<decimal> other { get; set; }
    }
}
